### ISSUE TITLE
Replace blocking Mutex with future Mutex

### ISSUE THREAD

**Issue by kpp** [tox-rs/tox#415]
Myabe with https://docs.rs/futures/0.3.5/futures/lock/struct.Mutex.html

**Comment by kpp** [comment]
@unseddd do you want to try?

**Comment by unseddd** [comment]
Definitely, will look into it. Totally failed with the async/await refactor attempt, maybe this will help.

**Comment by unseddd** [comment]
So... this is turning into a bit of a [Gordian Knot](https://en.wikipedia.org/wiki/Gordian_Knot). Get one piece working, and it breaks three or four other pieces.

Currently having something that compiles, but fails multiple tests (even hangs on one). Not sure if this is because of lock starvation, or...

Can post the work done so far, which is already a fairly sizable diff. Will continue hacking at it for another day or two, but starting to think a rewrite into less inter-dependent code may be more fruitful (i.e. many modules call into data members of other modules directly, instead of using a getter/setter API).

**Comment by 0623forbidden** [comment]
@kpp is it actual now? could I try?

**Comment by suhr** [comment]
I believe it is.

**Comment by kpp** [comment]
Yes

**Comment by NamsooCho** [comment]
@0623forbidden Great!!!

**Comment by kpp** [comment]
Fixed in https://github.com/tox-rs/tox/pull/434
